# 389. Find the Difference
"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

Example 2:
    Input: s = "", t = "y"
    Output: "y"
 
Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.

Solution: https://leetcode.com/problems/find-the-difference/description/
"""


from collections import defaultdict

def findTheDifference(s, t):
    count = defaultdict(int)
    for c in s:
        count[c] += 1

    for c in t:
        count[c] -= 1
        if count[c] < 0:
            return c


s = "abcd"
t = "abcde"

print(findTheDifference(s, t))
# Output: "e"

# count = {a:1, b:1, c:1, d:1} → returns 'e' (the extra letter in t)

# ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# Breakdown
from collections import defaultdict

def findTheDifference(s, t):
    count = defaultdict(int)    # Notebook to count each letter in s
    for c in s:                 # Go through each letter in s
        count[c] += 1           # Add 1 to this letter's count

    for c in t:                 # Go through each letter in t
        count[c] -= 1           # Use up one count for this letter
        if count[c] < 0:        # If we used more than s had
            return c            # This letter is the extra one in t


"""
Time: O(N)
  - Let N = length of s (t has length N + 1).
  - Step 1: Count each letter in s → O(N).
  - Step 2: Subtract counts while scanning t → O(N + 1).
      • May return early when the extra letter is found.
  - Combined: O(N + N) = O(N).
  - Overall: O(N).

Space: O(1)
  - count dictionary stores frequencies of lowercase English letters.
  - Maximum distinct keys = 26 → constant space (doesn't grow with N).
  - A few loop variables use O(1).
  - Overall: O(1) because of the "only a-z" constraint.

  If Unicode were allowed:
  - Space would be O(U), where U = number of unique characters.
  - Worst case: U ≈ N (if every char is different) → up to O(N) space.


Interview Answer: Worst Case

Time: O(N)
  - One pass to count letters in s, one pass to subtract using t.

Space: O(1) for lowercase English letters
  - Hash map holds at most 26 keys.


---
Overview for Each Iteration
Input: s = "abcd", t = "abcde"

Step 1: Count each letter in s
i | c | count
--|---|--------------------
- | - | {}
0 | a | {a:1}
1 | b | {a:1, b:1}
2 | c | {a:1, b:1, c:1}
3 | d | {a:1, b:1, c:1, d:1}

Step 2: Subtract using t
i | c | count[c] | <0? | Result
--|---|----------|-----|-----------
0 | a | 1→0      | No  | continue
1 | b | 1→0      | No  | continue
2 | c | 1→0      | No  | continue
3 | d | 1→0      | No  | continue
4 | e | 0→ -1    | Yes | return 'e'

Final: "e"


---
Most IMPORTANT thing to Understand:
    • t is just s with all its letters shuffled, plus one extra letter added somewhere.

    • Count how many times each letter appears in s, then subtract those counts while scanning t.

    • The first letter that makes the count go negative is the extra letter that was added to t.

---
Why this code Works:
    • Hash map role: count[c] tracks how many of each letter we still "expect" to see from s.

    • Technique: Add +1 for each letter in s, then -1 for each letter in t; the extra letter is the one that goes below zero.

    • Efficiency: One pass to build counts, one pass to subtract → O(N), no sorting required.

    • Intuition: Think of s as stocking a shelf and t as removing items. If you try to remove something that was never stocked, that item is the extra one.

---
TLDR:
    • Count letters from s, subtract using t, and return the first letter whose count goes negative.


---
Quick Example Walkthrough:

    s = "abcd"
    t = "abcde"

    Step 1 — Build counts from s:
        {'a':1, 'b':1, 'c':1, 'd':1}

    Step 2 — Process t:
        'a' → 1 → 0
        'b' → 1 → 0
        'c' → 1 → 0
        'd' → 1 → 0
        'e' → 0 → -1  →  return 'e'

    Final Answer: "e"


---
Full Example Walkthrough:
    s = "abcd"
    t = "abcde"

    Starting State:
        count = {} (empty defaultdict)

    --------------------------------------------------

    Loop 1 — Count letters in s:

    Iteration 1:
        c = 'a'
        count['a'] += 1

        Now:
            count = {'a': 1}

    --------------------------------------------------

    Iteration 2:
        c = 'b'
        count['b'] += 1

        Now:
            count = {'a': 1, 'b': 1}

    --------------------------------------------------

    Iteration 3:
        c = 'c'
        count['c'] += 1

        Now:
            count = {'a': 1, 'b': 1, 'c': 1}

    --------------------------------------------------

    Iteration 4:
        c = 'd'
        count['d'] += 1

        Now:
            count = {'a': 1, 'b': 1, 'c': 1, 'd': 1}

    --------------------------------------------------

    Loop 2 — Subtract using t:

    Iteration 1:
        c = 'a'
        count['a'] -= 1  →  1 → 0

        Check: count['a'] < 0?  No  →  continue

        Now:
            count = {'a': 0, 'b': 1, 'c': 1, 'd': 1}

    --------------------------------------------------

    Iteration 2:
        c = 'b'
        count['b'] -= 1  →  1 → 0

        Check: count['b'] < 0?  No  →  continue

        Now:
            count = {'a': 0, 'b': 0, 'c': 1, 'd': 1}

    --------------------------------------------------

    Iteration 3:
        c = 'c'
        count['c'] -= 1  →  1 → 0

        Check: count['c'] < 0?  No  →  continue

        Now:
            count = {'a': 0, 'b': 0, 'c': 0, 'd': 1}

    --------------------------------------------------

    Iteration 4:
        c = 'd'
        count['d'] -= 1  →  1 → 0

        Check: count['d'] < 0?  No  →  continue

        Now:
            count = {'a': 0, 'b': 0, 'c': 0, 'd': 0}

    --------------------------------------------------

    Iteration 5:
        c = 'e'
        count['e'] -= 1  →  0 → -1  (e was never in s, so it started at 0)

        Check: count['e'] < 0?  Yes  →  return 'e'

    --------------------------------------------------

    Final Answer:
        "e"

        This is the one letter in t that s did not have.


---
🧠 First Time? Thoughts → Code

Read the problem (10 sec)
    • t is s shuffled with one extra letter added — find that extra letter.

    • t is always exactly 1 character longer than s — only ONE letter is different in count.

    • Lowercase letters only — hint that counting frequencies is enough.


Start naive (totally fine)
    • Copy s into a list, walk through t, cross off matching letters.
    • First letter in t that isn't in the list (or can't be removed) is the answer.
    • Time: O(N²) — each letter may scan the whole list.


The one insight that unlocks the optimal code
    • Don't cross off one-by-one — count how many of each letter s has, then "spend" those counts on t.
    • t has the same letters as s except one extra — that letter's count goes negative first.
    • Same pattern as Valid Anagram — but return the letter instead of True/False.


Why a hash map?
    • You need "how many of each letter do I have?" not just "is this letter in s?"
    • defaultdict(int) starts missing letters at 0 — so the extra letter goes 0 → -1 automatically.
    • Only 26 possible keys — fast lookups, no sorting.


Thought → line of code
    count = defaultdict(int)
        → "Empty notebook — each letter starts at 0."

    for c in s: count[c] += 1
        → "Stock the shelf with everything s has."

    for c in t: count[c] -= 1
        → "Remove one of each letter t uses from my tally."

    if count[c] < 0: return c
        → "Went below zero — t used a letter s didn't have."
        → "That's the extra letter — return it immediately."


Memory hook (one sentence)
    • Count s, spend on t, first negative count is the added letter.


Would you arrive at this cold?
    • Immediately: cross letters off a copy of s while scanning t (the brute force).
    • After doing Valid Anagram: realize this is the same count-up / count-down pattern with a different return.
    • Bookkeeping: two loops, defaultdict — pattern you've seen before.
    • Real insight: negative count = extra letter. You'd only write `return c` instead of `return False` once you connect it to the anagram problem.


"""


# –––––––––––––––––––––––––––––––––––––––––––––––––––––––
# Brute force — List + remove (cross off letters from a copy of s)

def findTheDifference_bruteforce(s, t):
    available = list(s)

    for c in t:
        if c not in available:
            return c
        available.remove(c)


s = "abcd"
t = "abcde"
print(findTheDifference_bruteforce(s, t))
# Output: "e"


"""
Time: O(N²)
  - Let N = length of s (t has length N + 1).

  - Step 1: Copy s into a list → O(N).

  - Step 2: For each letter in t → O(N + 1) iterations.
      • c not in available scans the list → O(N).
      • available.remove(c) finds and removes → O(N).

  - Combined: O(N + N × N).
  - Overall: O(N²).


Space: O(N)
  - available list stores up to N letters from s.
  - Overall: O(N).


Interview Answer: Worst Case

Time: O(N²)
  - Each letter in t may scan the full list to check and remove.

Space: O(N)
  - Mutable copy of s as a list.


---
Overview for Each Iteration
Input: s = "abcd", t = "abcde"

    available starts = ['a', 'b', 'c', 'd']

    c = 'a' → in list → remove → ['b', 'c', 'd']
    c = 'b' → in list → remove → ['c', 'd']
    c = 'c' → in list → remove → ['d']
    c = 'd' → in list → remove → []
    c = 'e' → NOT in list → return 'e'

Final: "e"

"""







# 2. Sort both strings and compare
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s = sorted(s)
        t = sorted(t)

        for i in range(len(s)):
            if s[i] != t[i]:
                return t[i]

        return t[-1]

# Time: O(N log N) - Sort both strings, then one pass to compare.
# Space: O(N) - sorted copies of s and t.



# 3. XOR solution
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        ans = 0

        for c in s + t:
            ans ^= ord(c)

        return chr(ans)

# Time: O(N) - One pass over all characters in s and t.
# Space: O(1) - Only the ans variable; pairs cancel via XOR.
