# 389. Find the Difference
"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

Example 2:
    Input: s = "", t = "y"
    Output: "y"
 
Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.

Solution: https://leetcode.com/problems/find-the-difference/description/

NeetCode: https://neetcode.io/solutions/find-the-difference
"""


# Solution 1: Counter Frequency Check
from collections import Counter

def findTheDifference(s, t):
    count = Counter(s)          # O(N)

    for c in t:                 # O(N) iterations
        count[c] -= 1           # O(1)
        if count[c] < 0:        # O(1)
            return c


s = "abca"
t = "abcae"

print(findTheDifference(s, t))
# Output: "e"

# count = {a:2, b:1, c:1} → returns 'e' (the extra letter in t)

s = ""
t = "a"
print(findTheDifference(s, t))
# Output: "a"

# count = {} → 'a' goes 0 → -1 → returns 'a'

# ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# Breakdown
from collections import Counter

def findTheDifference(s, t):
    count = Counter(s)          # Notebook: how many of each letter s has

    for c in t:                 # Go through each letter in t
        count[c] -= 1           # Use up one count for this letter
        if count[c] < 0:        # If we used more than s had
            return c            # This letter is the extra one in t


"""
Time: O(N)
  - Let N = length of s (t has length N + 1).
  - Step 1: Counter(s) scans every letter in s once → O(N).
  - Step 2: Subtract count while scanning t → O(N + 1).
      • May return early when the extra letter is found.
  - Combined: O(N + N) = O(N).
  - Overall: O(N).

Space: O(1)
  - count stores frequencies of lowercase English letters.
  - Maximum distinct keys = 26 → constant space (doesn't grow with N).
  - A few loop variables use O(1).
  - Overall: O(1) because of the "only a-z" constraint.

  If Unicode were allowed:
  - Space would be O(U), where U = number of unique characters.
  - Worst case: U ≈ N (if every char is different) → up to O(N) space.


Interview Answer: Worst Case

Time: O(N)
  - One pass to count letters in s, one pass to subtract using t.

Space: O(1) for lowercase English letters
  - For lowercase English letters - Hash map holds at most 26 keys.


---
Most IMPORTANT thing to Understand:
    • t is just s with all its letters shuffled, plus one extra letter added somewhere.

    • Counter(s) tallies how many times each letter appears in s, then you subtract those counts while scanning t.

    • The first letter that makes the count go negative is the extra letter that was added to t.

    • Rule of thumb (two inputs, one dictionary):
          Count the expected / original input.
          Scan the one that might be extra, missing, or different.
          Here: s is expected → count s.  t has the extra letter → scan t.

---
Why this code Works:
    • Hash map role: count[c] tracks how many of each letter we still "expect" to see from s.

    • Technique: Counter(s) tallies s in one line, then -1 for each letter in t; the extra letter is the one that goes below zero.

    • Efficiency: One pass to build counts, one pass to subtract → O(N), no sorting required.

    • Intuition: Think of s as stocking a shelf and t as removing items. If you try to remove something that was never stocked, that item is the extra one.

---
TLDR:
    • Count the expected input (s), scan the one that might be extra (t), and return the first letter whose count goes negative.



    ---
    Overview for Each Iteration
    Input: s = "abca", t = "abcae"

    Step 1: Build Counter from s
    count = {a:2, b:1, c:1}

    Step 2: Subtract using t
    i | c | count[c] | <0? | Result
    --|---|----------|-----|-----------
    0 | a | 2→1      | No  | continue
    1 | b | 1→0      | No  | continue
    2 | c | 1→0      | No  | continue
    3 | a | 1→0      | No  | continue
    4 | e | 0→ -1    | Yes | return 'e'

    Final: "e"


---
Quick Example Walkthrough:

    s = "abca"
    t = "abcae"

    Step 1 — Build Counter from s:
        count = {'a':2, 'b':1, 'c':1}

    Step 2 — Process t:
        'a' → 2 → 1
        'b' → 1 → 0
        'c' → 1 → 0
        'a' → 1 → 0
        'e' → 0 → -1  →  return 'e'

    Final Answer: "e"


---
Full Example Walkthrough:
    s = "abca"
    t = "abcae"

    Starting State:
        count = Counter("abca") → {'a': 2, 'b': 1, 'c': 1}

    --------------------------------------------------

    Loop — Subtract using t:

    Iteration 1:
        c = 'a'
        count['a'] -= 1  →  2 → 1

        Check: count['a'] < 0?  No  →  continue

        Now:
            count = {'a': 1, 'b': 1, 'c': 1}

    --------------------------------------------------

    Iteration 2:
        c = 'b'
        count['b'] -= 1  →  1 → 0

        Check: count['b'] < 0?  No  →  continue

        Now:
            count = {'a': 1, 'b': 0, 'c': 1}

    --------------------------------------------------

    Iteration 3:
        c = 'c'
        count['c'] -= 1  →  1 → 0

        Check: count['c'] < 0?  No  →  continue

        Now:
            count = {'a': 1, 'b': 0, 'c': 0}

    --------------------------------------------------

    Iteration 4:
        c = 'a'
        count['a'] -= 1  →  1 → 0

        Check: count['a'] < 0?  No  →  continue

        Now:
            count = {'a': 0, 'b': 0, 'c': 0}

    --------------------------------------------------

    Iteration 5:
        c = 'e'
        count['e'] -= 1  →  0 → -1  (e was never in s, so it started at 0)

        Check: count['e'] < 0?  Yes  →  return 'e'

    --------------------------------------------------

    Final Answer:
        "e"

        This is the one letter in t that s did not have.


---
Quick Example Walkthrough:

    s = ""
    t = "a"

    Step 1 — Build Counter from s:
        count = {}  (s is empty — nothing to count)

    Step 2 — Process t:
        'a' → 0 → -1  →  return 'a'

    Final Answer: "a"






---
🧠 First Time? Thoughts → Code

Read the problem (10 sec)
    • t is s shuffled with one extra letter added — find that extra letter.

    • t is always exactly 1 character longer than s — only ONE letter is different in count.

    • Lowercase letters only — hint that counting frequencies is enough.


Start naive (totally fine)
    • Copy s into a list, walk through t, cross off matching letters.
    • First letter in t that isn't in the list (or can't be removed) is the answer.
    • Time: O(N²) — each letter may scan the whole list.


The one insight that unlocks the optimal code
    • Don't cross off one-by-one — count how many of each letter s has, then "spend" those counts on t.
    • t has the same letters as s except one extra — that letter's count goes negative first.
    • Same pattern as Valid Anagram — but return the letter instead of True/False.


Why a Counter / hash map?
    • You need "how many of each letter do I have?" not just "is this letter in s?"
    • A Counter treats missing letters as 0 — so the extra letter goes 0 → -1 automatically.
    • Only 26 possible keys — fast lookups, no sorting.


Thought → line of code
    count = Counter(s)
        → "Stock the shelf — tally every letter in s before I start spending."

    for c in t:
        → "Walk each letter t uses, one at a time."

    count[c] -= 1
        → "Remove one of this letter from my tally."

    if count[c] < 0: return c
        → "Went below zero — t used a letter s didn't have."
        → "That's the extra letter — return it immediately."


Memory hook (one sentence)
    • Count s, spend on t, first negative count is the added letter.


Would you arrive at this cold?
    • Immediately: cross letters off a copy of s while scanning t (the brute force).
    • After doing Valid Anagram: realize this is the same count-up / count-down pattern with a different return.
    • Bookkeeping: build a Counter, loop the other string — pattern you've seen before.
    • Real insight: negative count = extra letter. You'd only write `return c` instead of `return False` once you connect it to the anagram problem.


"""



# –––––––––––––––––––––––––––––––––––––––––––––––––––––––
# Brute force — List + remove (cross off letters from a copy of s)

def findTheDifference_bruteforce(s, t):
    available = list(s)          # O(N) copy

    for c in t:                  # O(N) iterations
        if c not in available:   # O(N) scan
            return c
        available.remove(c)      # O(N) find + shift


s = "abca"
t = "abcae"
print(findTheDifference_bruteforce(s, t))
# Output: "e"


"""
Time: O(N²)
  - Let N = length of s. t has N + 1 letters.

  - available = list(s) → O(N)

  - The loop runs O(N) times.
    Inside each loop:
      • c not in available → O(N)
      • available.remove(c) → O(N)

  - Work inside one loop:
      O(N) + O(N) = O(N)

  - That O(N) work happens O(N) times:
      O(N) × O(N) = O(N²)

  - Including the initial copy:
      O(N) + O(N²) = O(N²)

  - Overall: O(N²).


Space: O(N)
  - available stores a copy of the N letters in s.
  - Overall: O(N).


Interview Answer: Worst Case

Time: O(N²)
  - O(N) loop iterations, with O(N) list work inside each iteration.
  - Each letter in t may scan the full list to check and remove.

Space: O(N)
  - Stores a mutable copy of s as a list.


---
Overview for Each Iteration
Input: s = "abca", t = "abcae"

    available starts = ['a', 'b', 'c', 'a']

    c = 'a' → in list → remove → ['b', 'c', 'a']
    c = 'b' → in list → remove → ['c', 'a']
    c = 'c' → in list → remove → ['a']
    c = 'a' → in list → remove → []
    c = 'e' → NOT in list → return 'e'

Final: "e"

"""


# –––––––––––––––––––––––––––––––––––––––––––––––––––––––
# Solution 2: Two Counter Comparison
from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        count_s, count_t = Counter(s), Counter(t)  # O(N)

        for c in count_t:                          # O(1) — at most 26 keys
            if c not in count_s or count_s[c] < count_t[c]:  # O(1)
                return c

# Time: O(N) - Count both strings, then compare unique letters in t.
# Space: O(1) for lowercase English letters - Two hash maps, at most 26 keys each.


# –––––––––––––––––––––––––––––––––––––––––––––––––––––––
# 3. Sort both strings and compare
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s = sorted(s)                # O(N log N)
        t = sorted(t)                # O(N log N)

        for i in range(len(s)):      # O(N)
            if s[i] != t[i]:         # O(1)
                return t[i]

        return t[-1]                 # O(1)

# Time: O(N log N) - Sort both strings, then one pass to compare.
# Space: O(N) - sorted copies of s and t.


# –––––––––––––––––––––––––––––––––––––––––––––––––––––––
# 4. XOR solution
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        ans = 0                      # O(1)

        for c in s + t:              # O(N) iterations
            ans ^= ord(c)            # O(1)

        return chr(ans)              # O(1)

# Time: O(N) - One pass over all characters in s and t.
# Space: O(1) - Only the ans variable; pairs cancel via XOR.
